package ch.trancee.meshlink.crypto

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Run all Wycheproof test vectors (984 vectors) against the platform CryptoProvider.
 *
 * Covers edge cases that RFC reference vectors don't: malleability, non-canonical
 * encodings, low-order points, truncated signatures, Poly1305 edge cases, etc.
 *
 * Vectors are generated by `scripts/generate-wycheproof-vectors.sh` from Google's
 * Wycheproof repository.
 */
class WycheproofCryptoTest {

    private val provider: CryptoProvider = createCryptoProvider()

    // ── Ed25519 — 150 vectors ────────────────────────────────────────────────

    @Test
    fun ed25519ValidVectorsMustVerify() {
        val valid = WycheproofEd25519Vectors.vectors.filter { it.valid }
        assertTrue(valid.isNotEmpty(), "Must have valid Ed25519 vectors")
        for (v in valid) {
            assertTrue(
                provider.verify(v.publicKey, v.msg, v.sig),
                "Ed25519 tc${v.tcId} must verify (${v.comment})",
            )
        }
    }

    @Test
    fun ed25519InvalidVectorsMustReject() {
        val invalid = WycheproofEd25519Vectors.vectors.filter { !it.valid }
        assertTrue(invalid.isNotEmpty(), "Must have invalid Ed25519 vectors")
        for (v in invalid) {
            // Invalid vectors must either return false or throw.
            // libsodium's verify returns false for malformed signatures;
            // some implementations throw on malformed input.
            val verified =
                try {
                    provider.verify(v.publicKey, v.msg, v.sig)
                } catch (_: Exception) {
                    false
                }
            assertFalse(
                verified,
                "Ed25519 tc${v.tcId} must NOT verify (${v.comment}, flags=${v.flags})",
            )
        }
    }

    // ── X25519 — 518 vectors ─────────────────────────────────────────────────

    @Test
    fun x25519ValidVectorsMatchExpected() {
        val valid = WycheproofX25519Vectors.vectors.filter { it.result == "valid" }
        assertTrue(valid.isNotEmpty(), "Must have valid X25519 vectors")
        for (v in valid) {
            val shared = provider.x25519SharedSecret(v.privateKey, v.publicKey)
            assertContentEquals(
                v.sharedSecret,
                shared,
                "X25519 tc${v.tcId} shared secret mismatch (${v.comment})",
            )
        }
    }

    @Test
    fun x25519AcceptableVectorsMatchOrReject() {
        // "acceptable" means the computation is well-defined but the input is non-standard
        // (non-canonical public key, low-order point, etc.).
        //
        // Behavior for acceptable vectors is implementation-defined:
        //   - libsodium: reduces non-canonical public keys, returns all-zero for low-order points
        //   - JDK: may compute different results for non-canonical inputs
        //   - Some implementations: reject outright (throw)
        // All behaviors are valid. We verify: the operation either succeeds with 32-byte output
        // or throws — it must not silently corrupt or return wrong-length data.
        val acceptable = WycheproofX25519Vectors.vectors.filter { it.result == "acceptable" }
        assertTrue(acceptable.isNotEmpty(), "Must have acceptable X25519 vectors")
        var completed = 0
        var rejected = 0
        for (v in acceptable) {
            val shared =
                try {
                    provider.x25519SharedSecret(v.privateKey, v.publicKey)
                } catch (_: Exception) {
                    rejected++
                    continue
                }
            assertTrue(
                shared.size == 32,
                "X25519 tc${v.tcId} must produce 32-byte output (${v.comment})",
            )
            completed++
        }
        // Sanity: at least some vectors should have completed (not all rejected).
        assertTrue(completed > 0, "Expected some acceptable vectors to compute successfully")
    }

    // ── ChaCha20-Poly1305 IETF AEAD — 316 vectors ───────────────────────────

    @Test
    fun aeadValidVectorsEncryptCorrectly() {
        val valid = WycheproofAeadVectors.vectors.filter { it.valid }
        assertTrue(valid.isNotEmpty(), "Must have valid AEAD vectors")
        for (v in valid) {
            val ct = provider.aeadEncrypt(v.key, v.nonce, v.plaintext, v.aad)
            assertContentEquals(
                v.ciphertextWithTag,
                ct,
                "AEAD encrypt tc${v.tcId} mismatch (${v.comment})",
            )
        }
    }

    @Test
    fun aeadValidVectorsDecryptCorrectly() {
        val valid = WycheproofAeadVectors.vectors.filter { it.valid }
        for (v in valid) {
            val pt = provider.aeadDecrypt(v.key, v.nonce, v.ciphertextWithTag, v.aad)
            assertContentEquals(
                v.plaintext,
                pt,
                "AEAD decrypt tc${v.tcId} mismatch (${v.comment})",
            )
        }
    }

    @Test
    fun aeadInvalidVectorsMustRejectDecryption() {
        val invalid = WycheproofAeadVectors.vectors.filter { !it.valid }
        assertTrue(invalid.isNotEmpty(), "Must have invalid AEAD vectors")
        for (v in invalid) {
            // Invalid vectors have modified tags, wrong keys, or corrupted ciphertext.
            // Decryption must throw (libsodium returns -1 → CryptoProvider wraps as exception).
            assertFailsWith<Exception>(
                "AEAD decrypt tc${v.tcId} must reject (${v.comment}, flags=${v.flags})",
            ) {
                provider.aeadDecrypt(v.key, v.nonce, v.ciphertextWithTag, v.aad)
            }
        }
    }
}
