#!/usr/bin/env bash
# scripts/generate-wycheproof-vectors.sh
# Generate Kotlin Wycheproof test vector source files from upstream JSON.
#
# Downloads test vector JSON files from Google's Wycheproof repository and
# generates Kotlin source files with embedded test vectors for:
#   - Ed25519 sign/verify      (150 vectors)
#   - X25519 Diffie-Hellman    (518 vectors)
#   - ChaCha20-Poly1305 AEAD   (316 vectors, IETF 96-bit nonce only)
#
# Requires: bash, curl, jq
#
# Usage: bash scripts/generate-wycheproof-vectors.sh
#
# Output:
#   meshlink/src/commonTest/kotlin/ch/trancee/meshlink/crypto/WycheproofEd25519Vectors.kt
#   meshlink/src/commonTest/kotlin/ch/trancee/meshlink/crypto/WycheproofX25519Vectors.kt
#   meshlink/src/commonTest/kotlin/ch/trancee/meshlink/crypto/WycheproofAeadVectors.kt
set -euo pipefail

for cmd in curl jq; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "ERROR: $cmd is required but not found." >&2
        exit 1
    fi
done

WYCHEPROOF_BASE="https://raw.githubusercontent.com/google/wycheproof/master/testvectors_v1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUT_DIR="${PROJECT_ROOT}/meshlink/src/commonTest/kotlin/ch/trancee/meshlink/crypto"

TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

mkdir -p "${OUT_DIR}"

# ── Download ──────────────────────────────────────────────────────────────────

download() {
    local name="$1"
    local url="${WYCHEPROOF_BASE}/${name}"
    local dest="${TMPDIR}/${name}"
    echo "  Downloading ${name}..." >&2
    curl -fsSL "${url}" -o "${dest}"
    echo "${dest}"
}

ED25519_JSON="$(download ed25519_test.json)"
X25519_JSON="$(download x25519_test.json)"
AEAD_JSON="$(download chacha20_poly1305_test.json)"

# ── Ed25519 ───────────────────────────────────────────────────────────────────

generate_ed25519() {
    local OUT="${OUT_DIR}/WycheproofEd25519Vectors.kt"
    local TOTAL VALID INVALID

    TOTAL="$(jq '[.testGroups[].tests[]] | length' "${ED25519_JSON}")"
    VALID="$(jq '[.testGroups[].tests[] | select(.result == "valid")] | length' "${ED25519_JSON}")"
    INVALID="$(jq '[.testGroups[].tests[] | select(.result == "invalid")] | length' "${ED25519_JSON}")"

    {
        cat <<HEADER
package ch.trancee.meshlink.crypto

/**
 * Ed25519 test vectors from Google Wycheproof (${TOTAL} vectors: ${VALID} valid, ${INVALID} invalid).
 *
 * Generated by scripts/generate-wycheproof-vectors.sh — do not edit.
 *
 * Source: https://github.com/google/wycheproof/blob/master/testvectors_v1/ed25519_test.json
 */
object WycheproofEd25519Vectors {

    data class Vector(
        val tcId: Int,
        val publicKey: ByteArray,
        val msg: ByteArray,
        val sig: ByteArray,
        val valid: Boolean,
        val comment: String,
        val flags: List<String>,
    )

    val vectors: List<Vector> = listOf(
HEADER

        # Flatten groups → vectors, emitting one Kotlin line per vector
        jq -r '
            .testGroups[] as $g |
            $g.tests[] |
            "        Vector(\(.tcId), \"\($g.publicKey.pk)\".hexToByteArray(), "
            + (if .msg == "" then "byteArrayOf()" else "\"\(.msg)\".hexToByteArray()" end)
            + ", \"\(.sig)\".hexToByteArray(), "
            + (if .result == "valid" then "true" else "false" end)
            + ", \"\(.comment | gsub("\""; "\\\\\""))\", listOf("
            + ([.flags[] | "\"" + . + "\""] | join(", "))
            + ")),"
        ' "${ED25519_JSON}"

        echo "    )"
        echo "}"
        echo ""
    } > "${OUT}"

    echo "  → $(basename "${OUT}") (${TOTAL} vectors)"
}

# ── X25519 ────────────────────────────────────────────────────────────────────

generate_x25519() {
    local OUT="${OUT_DIR}/WycheproofX25519Vectors.kt"
    local TOTAL VALID ACCEPTABLE

    TOTAL="$(jq '[.testGroups[].tests[]] | length' "${X25519_JSON}")"
    VALID="$(jq '[.testGroups[].tests[] | select(.result == "valid")] | length' "${X25519_JSON}")"
    ACCEPTABLE="$(jq '[.testGroups[].tests[] | select(.result == "acceptable")] | length' "${X25519_JSON}")"

    {
        cat <<HEADER
package ch.trancee.meshlink.crypto

/**
 * X25519 test vectors from Google Wycheproof (${TOTAL} vectors: ${VALID} valid, ${ACCEPTABLE} acceptable).
 *
 * Generated by scripts/generate-wycheproof-vectors.sh — do not edit.
 *
 * Source: https://github.com/google/wycheproof/blob/master/testvectors_v1/x25519_test.json
 *
 * Acceptable vectors have non-canonical public keys or produce low-order shared secrets.
 * libsodium's crypto_scalarmult handles these correctly (clamping, canonical reduction).
 * Vectors flagged ZeroSharedSecret must be rejected (all-zero output).
 */
object WycheproofX25519Vectors {

    data class Vector(
        val tcId: Int,
        val publicKey: ByteArray,
        val privateKey: ByteArray,
        val sharedSecret: ByteArray,
        val result: String,
        val comment: String,
        val flags: List<String>,
    )

    val vectors: List<Vector> = listOf(
HEADER

        jq -r '
            .testGroups[].tests[] |
            "        Vector(\(.tcId), \"\(.public)\".hexToByteArray(), \"\(.private)\".hexToByteArray(), \"\(.shared)\".hexToByteArray(), \"\(.result)\", \"\(.comment | gsub("\""; "\\\\\""))\", listOf("
            + ([.flags[] | "\"" + . + "\""] | join(", "))
            + ")),"
        ' "${X25519_JSON}"

        echo "    )"
        echo "}"
        echo ""
    } > "${OUT}"

    echo "  → $(basename "${OUT}") (${TOTAL} vectors)"
}

# ── ChaCha20-Poly1305 ────────────────────────────────────────────────────────

generate_aead() {
    local OUT="${OUT_DIR}/WycheproofAeadVectors.kt"

    # Only IETF-standard: 96-bit nonce, 128-bit tag
    local TOTAL VALID INVALID
    TOTAL="$(jq '[.testGroups[] | select(.ivSize == 96 and .tagSize == 128) | .tests[]] | length' "${AEAD_JSON}")"
    VALID="$(jq '[.testGroups[] | select(.ivSize == 96 and .tagSize == 128) | .tests[] | select(.result == "valid")] | length' "${AEAD_JSON}")"
    INVALID="$(jq '[.testGroups[] | select(.ivSize == 96 and .tagSize == 128) | .tests[] | select(.result == "invalid")] | length' "${AEAD_JSON}")"

    {
        cat <<HEADER
package ch.trancee.meshlink.crypto

/**
 * ChaCha20-Poly1305 IETF AEAD test vectors from Google Wycheproof (${TOTAL} vectors: ${VALID} valid, ${INVALID} invalid).
 *
 * Generated by scripts/generate-wycheproof-vectors.sh — do not edit.
 *
 * Source: https://github.com/google/wycheproof/blob/master/testvectors_v1/chacha20_poly1305_test.json
 *
 * Only vectors with 96-bit nonce and 128-bit tag (IETF standard) are included.
 * The [ciphertextWithTag] field is ct || tag (matching libsodium's output format).
 */
object WycheproofAeadVectors {

    data class Vector(
        val tcId: Int,
        val key: ByteArray,
        val nonce: ByteArray,
        val aad: ByteArray,
        val plaintext: ByteArray,
        val ciphertextWithTag: ByteArray,
        val valid: Boolean,
        val comment: String,
        val flags: List<String>,
    )

    val vectors: List<Vector> = listOf(
HEADER

        # Filter to ivSize=96, tagSize=128; concatenate ct+tag for libsodium format
        jq -r '
            .testGroups[] | select(.ivSize == 96 and .tagSize == 128) |
            .tests[] |
            "        Vector(\(.tcId), \"\(.key)\".hexToByteArray(), \"\(.iv)\".hexToByteArray(), "
            + (if .aad == "" then "byteArrayOf()" else "\"\(.aad)\".hexToByteArray()" end)
            + ", "
            + (if .msg == "" then "byteArrayOf()" else "\"\(.msg)\".hexToByteArray()" end)
            + ", \"\(.ct)\(.tag)\".hexToByteArray(), "
            + (if .result == "valid" then "true" else "false" end)
            + ", \"\(.comment | gsub("\""; "\\\\\""))\", listOf("
            + ([.flags[] | "\"" + . + "\""] | join(", "))
            + ")),"
        ' "${AEAD_JSON}"

        echo "    )"
        echo "}"
        echo ""
    } > "${OUT}"

    echo "  → $(basename "${OUT}") (${TOTAL} vectors)"
}

# ── Main ──────────────────────────────────────────────────────────────────────

echo "Generating Wycheproof test vectors..."
generate_ed25519
generate_x25519
generate_aead
echo "Done."
